import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { ReactElement } from "react";
import "./globals.css";
import { ThemeStateProvider } from "@/theme";
import { ResponsiveAppBar } from "@/layout/nav";
import { Box, Paper, Stack } from "@mui/material";
// import { getStaticParams } from '../../locales/server';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Uncomment to test Static Generation for all pages
// export function generateStaticParams() {
//   return getStaticParams();
// }

export default function RootLayout({ children }: { children: ReactElement }) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeStateProvider>
            {/* Uncomment the suspense boundary if using `preserveSearchParams` in `useChangeLocale()` */}
            {/* <Suspense> */}
            {/* <Switch /> */}
            {/* </Suspense> */}
            <Stack direction={"column"} sx={{ height: "100vh" }}>
              <ResponsiveAppBar />
              <Paper
                elevation={0}
                sx={{
                  flex: 1,
                  borderRadius: 0,
                  overflowX: "hidden",
                  overflowY: "auto",
                }}
              >
                {children}
              </Paper>
            </Stack>
          </ThemeStateProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
