import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/theme";
import type { ReactElement } from "react";
import "./globals.css";
import { Switch } from "./switch";
import Link from "next/link";
import { Typography } from "@mui/material";
// import { getStaticParams } from '../../locales/server';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Uncomment to test Static Generation for all pages
// export function generateStaticParams() {
//   return getStaticParams();
// }

export default function RootLayout({ children }: { children: ReactElement }) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            {/* Uncomment the suspense boundary if using `preserveSearchParams` in `useChangeLocale()` */}
            {/* <Suspense> */}
            <Switch />
            {/* </Suspense> */}
            <ul>
              <li>
                <Link href="/">
                  <Typography>Go to /</Typography>
                </Link>
              </li>
              <li>
                <Link href="/subpage">
                  <Typography>Go to /subpage</Typography>
                </Link>
              </li>
              <li>
                <Link href="/client">
                  <Typography>Go to /client</Typography>
                </Link>
              </li>
            </ul>
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
